name = "tiny-poly"
defaultTargets = [
  "TinyPoly",
  "demo",
  "vending",
  "pipeline",
  "workflow",
  "counter",
  "dfa",
  "file_reader",
  "square",
  "streams",
  "arrow_field",
  "life",
  "tests",
]

[[lean_lib]]
name = "TinyPoly"

[[lean_exe]]
name = "demo"
root = "Main"

[[lean_exe]]
name = "vending"
root = "Examples.Vending"

[[lean_exe]]
name = "pipeline"
root = "Examples.Pipeline"

[[lean_exe]]
name = "workflow"
root = "Examples.Workflow"

[[lean_exe]]
name = "counter"
root = "Examples.Counter"

[[lean_exe]]
name = "dfa"
root = "Examples.Dfa"

[[lean_exe]]
name = "file_reader"
root = "Examples.FileReader"

[[lean_exe]]
name = "square"
root = "Examples.Square"

[[lean_exe]]
name = "streams"
root = "Examples.Streams"

[[lean_exe]]
name = "arrow_field"
root = "Examples.ArrowField"

[[lean_exe]]
name = "life"
root = "Examples.Life"

[[lean_exe]]
name = "tests"
root = "Tests"
